openapi:
  statistic:
    enabled: true
spring:
  datasource:
#    url: jdbc:mysql://114.116.41.228:7878/opcr?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
#    username: root
#    password: '123qwe!QAZ'
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    host: 10.2.34.31
#    port: 6379
#    password: '123456'
     host: 114.116.47.6
     port: 9001
     password: '123qwe!@#QWE'
logging:
  config: classpath:logback-async.xml
  file:
    path: D:/logs
